name: React Quill Editor Continous Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build # 업로드 할 빌드 파일 생성

      - uses: actions/upload-artifact@v3 # 빌드 결과물을 업로드하고 다운가능한 상태로 보여주는 액션
        with:
          name: built-artifact
          path: build/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: built-artifact

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # AWS credential을 github action과 연동
        with:
          role-to-assume: arn:aws:iam::635275223949:user/hyuna-github-workflow
          aws-region: ap-northeast-2
