name: React Quill Editor Continous Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci # 기존 모듈 삭제 및 패키지 설치

      - name: Build app
        run: npm run build # 업로드 할 빌드 파일 생성

      - uses: actions/upload-artifact@v3 # 빌드 결과물을 업로드하고 다운가능한 상태로 보여주는 액션
        with:
          name: built-artifact
          path: build/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3 # 빌드 결과물을 다운로드 해주는 액션
        with:
          name: built-artifact
          
      - name: Find build dir
        run: ls -al
             
      - name: PWD
        run: pwd
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # AWS credential을 github action과 연동
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload CSS, JS, Assets to S3 # S3에 static 파일 업로드
        run: aws s3 sync ./out s3://react-quill-editor-example
